- name: Ping Test
  hosts: catalogue
  tasks:
    - name: pinging the catalogue server
      ansible.builtin.ping:

    - name: Display a message
      ansible.builtin.debug:    # Display a custom message after successful ping debug is used intead of echo module
        msg: "Ping test to catalogue server was successful!"